# Generated by Django 4.1.1 on 2022-10-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='school',
            new_name='unit',
        ),
        migrations.RemoveField(
            model_name='department',
            name='school',
        ),
        migrations.AddField(
            model_name='department',
            name='unit',
            field=models.CharField(default=1, max_length=32, verbose_name='单位'),
            preserve_default=False,
        ),
    ]
