# Generated by Django 4.1.1 on 2022-10-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0002_rename_school_user_unit_remove_department_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别'),
        ),
    ]
