# Generated by Django 4.1.6 on 2023-03-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0004_alter_user_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='entry_date',
            field=models.DateField(default='1999-01-01', verbose_name='入职时间'),
        ),
    ]
