# Generated by Django 4.1.6 on 2023-03-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0005_user_entry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='项目')),
                ('budget', models.IntegerField(max_length=16, verbose_name='预算')),
                ('level', models.SmallIntegerField(choices=[(1, 'A级'), (2, 'B级'), (3, 'C级')], default=3, verbose_name='等级')),
                ('status', models.SmallIntegerField(choices=[(1, '未启动'), (2, '进行中'), (3, '待交付'), (4, '已结束')], default=1, verbose_name='状态')),
            ],
        ),
    ]
