# Generated by Django 4.1.6 on 2023-03-03 04:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0006_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='mobile',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator('^1\\d{10}$|^\\d{7}$')], verbose_name='部门电话'),
        ),
        migrations.AlterField(
            model_name='department',
            name='unit',
            field=models.CharField(max_length=32, verbose_name='部门名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.IntegerField(verbose_name='预算'),
        ),
    ]
