# Generated by Django 4.1.6 on 2023-03-03 07:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0008_alter_department_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='mobile',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator('^1\\d{10}$|^\\d{7}$', '电话格式错误')], verbose_name='部门电话'),
        ),
    ]
