# Generated by Django 4.1.6 on 2023-03-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0009_alter_department_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='mobile',
            field=models.CharField(blank=True, max_length=16, verbose_name='部门电话'),
        ),
    ]
