# Generated by Django 4.1.6 on 2023-03-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0011_suer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suer',
            new_name='Su',
        ),
        migrations.RenameField(
            model_name='su',
            old_name='suer',
            new_name='su',
        ),
    ]
